# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_xdf <- function(filename_, stream_ids = NULL) {
    .Call(`_rxdf_load_xdf`, filename_, stream_ids)
}

